"""Unit and Integration Tests for Physical Camera Connectors and Dynamic Hotplug.

The clips these tests probe are generated by the ``sample_video`` fixture, not
named on disk. An earlier version referenced ``vid_01_retail_walkway.mp4`` by
bare relative path, which passed only on a machine that happened to have that
file in its working directory and failed everywhere else.
"""

from __future__ import annotations

from pathlib import Path

from vantage.dashboard.api import DashboardApi
from vantage.ingestion.connectors.discovery import CameraDiscoveryService
from vantage.ingestion.connectors.manager import CameraConnectorManager
from vantage.multicam.pipeline import MultiCameraPipeline


def test_vendor_rtsp_presets() -> None:
    discovery = CameraDiscoveryService()
    presets = discovery.get_presets()
    assert "hikvision_main" in presets
    assert "dahua_main" in presets
    assert "axis" in presets
    assert "reolink" in presets
    assert "tapo" in presets


def test_camera_connection_test_valid_media(sample_video: Path) -> None:
    discovery = CameraDiscoveryService()
    res = discovery.test_camera_connection(str(sample_video))
    assert res["status"] == "connected"
    assert res["width"] > 0
    assert res["height"] > 0
    assert "thumbnail" in res
    assert res["thumbnail"].startswith("data:image/jpeg;base64,")


def test_camera_connection_test_invalid_stream() -> None:
    discovery = CameraDiscoveryService()
    # Non-existent RTSP host
    res = discovery.test_camera_connection("rtsp://192.0.2.1:554/invalid_stream_path")
    assert res["status"] == "error"
    assert "error" in res


def test_dynamic_camera_hotplug_attach_and_detach(sample_video: Path) -> None:
    pipeline = MultiCameraPipeline(
        camera_sources={"cam_01": str(sample_video)},
        model="yolox-nano",
        conf_threshold=0.35,
        enable_pose=False,
    )
    assert len(pipeline.workers) == 1

    manager = CameraConnectorManager()

    # 1. Dynamically attach a 2nd camera
    res = manager.attach_camera(
        pipeline=pipeline,
        camera_id="cam_02_dynamic",
        name="Dynamic Test Gate",
        uri=str(sample_video),
        mount_x=15.0,
        mount_y=3.2,
        mount_z=8.0,
    )
    assert res["status"] == "ok"
    assert res["camera_id"] == "cam_02_dynamic"
    assert len(pipeline.workers) == 2
    assert "cam_02_dynamic" in pipeline.spatial_twin.camera_mounts

    # 2. Duplicate attachment should return error
    res_dup = manager.attach_camera(
        pipeline=pipeline,
        camera_id="cam_02_dynamic",
        name="Duplicate",
        uri=str(sample_video),
    )
    assert res_dup["status"] == "error"

    # 3. Dynamically detach the 2nd camera
    res_del = manager.detach_camera(pipeline=pipeline, camera_id="cam_02_dynamic")
    assert res_del["status"] == "ok"
    assert len(pipeline.workers) == 1
    assert "cam_02_dynamic" not in pipeline.spatial_twin.camera_mounts

    # Stop pipeline
    pipeline.stop()


def test_dashboard_camera_api_endpoints(sample_video: Path) -> None:
    pipeline = MultiCameraPipeline(
        camera_sources={"cam_01": str(sample_video)},
        model="yolox-nano",
        enable_pose=False,
    )
    api = DashboardApi(pipeline=pipeline, spatial_twin=pipeline.spatial_twin)

    # 1. GET /api/cameras
    cams_res = api.handle("cameras", {})
    assert cams_res["count"] == 1
    assert cams_res["cameras"][0]["camera_id"] == "cam_01"

    # 2. GET /api/cameras/presets
    presets_res = api.handle("cameras/presets", {})
    assert "presets" in presets_res

    # 3. POST /api/cameras/test
    test_res = api.handle_post("cameras/test", {"uri": str(sample_video)})
    assert test_res["status"] == "connected"

    # 4. POST /api/cameras/connect
    connect_res = api.handle_post(
        "cameras/connect",
        {
            "camera_id": "cam_live_test",
            "name": "Live Test Cam",
            "uri": str(sample_video),
            "mount_x": 10.0,
            "mount_y": 3.0,
            "mount_z": 10.0,
        },
    )
    assert connect_res["status"] == "ok"
    assert len(pipeline.workers) == 2

    # 5. DELETE /api/cameras
    del_res = api.handle_delete("cameras", {"id": "cam_live_test"})
    assert del_res["status"] == "ok"
    assert len(pipeline.workers) == 1

    pipeline.stop()
